### ISSUE TITLE
Feature Request - Write to scratch layer

### ISSUE THREAD

**Issue by kylesomerville** [borysiasty/pointsamplingtool#12]
Great tool but the need to save to a permanent shapefile can leave a lot of cleaning up to do - are there any plans afoot to allow saving to scratch later, or to incorporate the plugin as a Processing Toolbox function?

**Comment by borysiasty** [comment]
Hi, I don't have any plans for further development, although maybe I'll find some time for the scratch layer some day. Please note the recent version (for QGIS 3) can also save to GeoPackage, so there is far less files to remove ;) 

Also there is a new Processing algorithm called 'Raster pixels to points' (from QGIS 3.0 or 3.2 - I can't recall), unfortunately no such tool for polygons yet. The Point Sampling Tool plugin won't be included to the Processing because of its interactive interface (and to not duplicate the Raster Pixels to Points algorithm).
