### ISSUE TITLE
bug of instalation of point sampling tool

### ISSUE THREAD

**Issue by BOTOXE** [borysiasty/pointsamplingtool#6]
provide an error message ''Échec de l'installation:La poignée de main SSL a échoué ''

**Comment by borysiasty** [comment]
What QGIS version?

**Comment by BOTOXE** [comment]
Qgis version 2.6.1-1

**Comment by borysiasty** [comment]
There were some changes in the plugin repository recently, affecting SSL. It may be, so old QGIS can't cope with it, so I'd try with more contemporary QGIS version first. Otherwise it looks like a problem with your network or proxy settings.

Anyway, it's not related with the plugin itself, rather with the connection between QGIS and the plugin repository.
